---
apiVersion: v1
kind: Pod
metadata:
  name: sample 
spec:
  containers:
    - name: webservice
      image: raghudevops29/httpd:v1
    - name: centos
      image: centos 
      command: [ "sleep" ]
      args: [ "1000" ]
