apiVersion: v1
kind: Pod
metadata:
  name: sample1
spec:
  containers:
    - name: mariadb 
      image: mariadb
      env:
      - name: MYSQL_ROOT_PASSWORD
        value: root
      volumeMounts:
      - mountPath: /var/lib/mysql
        name: dbvolume
  volumes:
  - name: dbvolume
    gcePersistentDisk:
      pdName: dbdisk
      fsType: ext4
