---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    matchLabels:
      PROJ: student
  template:
    metadata:
      labels:
        PROJ: student
    spec:
      containers:
        - name: mariadb 
          image: mariadb
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: dbvolume
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root

        - name: studentapp
          image: raghudevops29/student:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      volumes:
      - name: dbvolume
        gcePersistentDisk:
          pdName: mariadb-disk
          fsType: ext4
...

---
kind: Service
apiVersion: v1
metadata:
  name: web-svc
spec:
  type: LoadBalancer
  selector:
    PROJ: student
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
... 


