---
apiVersion: v1
kind: Pod
metadata:
  name: stack 
spec:
  containers:
    - name: mariadb 
      image: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root

    - name: studentapp
      image: raghudevops29/student:v2 
      imagePullPolicy: Always 
